import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const exo = Exo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
